### ISSUE TITLE
Simplifier l'alignement dans les classes .col

### ISSUE THREAD

**Issue by martinsam** [nico3333fr/ROCSSTI#19]
Pour aligner verticalement du contenu dans un "bloc", actuellement il est nécessaire d'utiliser les classes suivantes : 

col-noalign alignbottom

Côté HTML, sémantiquement parlant c'est pertubant. Cela revient à dire "Je ne souhaite pas utiliser d'alignement et puis je demande un alignement bottom".

Peut t'on imaginer la suppression de vertical-align: top de la classe col pour pouvoir utiliser : 
"col alignbottom" tout simplement ?  

Y a t'il un risque à ne pas définir explicitement vertical-align ?

**Comment by nico3333fr** [comment]
Dans les toutes premières versions de Röcssti, c'est ce que j'avais fait, et du coup, tu devais mettre systématiquement aligntop (c'est un vertical-align: middle qui est par défaut appliqué si je ne me trompe pas).

En pratique, après une dizaine de sites, on a décidé de mettre vertical-align: top par défaut sur .col, car la très grosse majorité de nos cas, on se sert de .col pour faire des mises en page en colonne (curieusement, le centrage vertical sur un .col est plutôt rare, je dirais que c'est à peine 10% de mes cas, pour ça que j'ai mis le plus court sur le plus utilisé, raison de pure fainéantise).

Le seul risque que je vois à ne pas définir explicitement vertical-align est d'avoir un comportement non "garanti" (typiquement un principe d'OOCSS, un objet doit être prévisible) : suffit d'être dans un cas foireux (un .col pris dans un autre dont l'alignement n'est pas défini) pour que ça fasse des bizarreries.

Voilou, tu as l'histoire complète :)

**Comment by tzi** [comment]
Je suis d'accord sur le fait que le `vertical-align` doit être à top par défaut.
Ne serait-ce pas possible de déclarer les classes `.aligntop`, `.alignmiddle`, `.alignbottom` après les déclarations de `.col` ?
Ainsi plus besoin de penser à mettre la classe `.col-noalign`.

A bientôt.
Thomas ;)

**Comment by nico3333fr** [comment]
Yop,

mais c'est pas con ça. :D
(mon collègue me signale que je lui en avais parlé, mais que du coup c'était resté sans suite)

Dans ce cas, je déplacerais `.aligntop`, `.alignmiddle`, `.alignbottom` juste après le table layout, effectivement.

J'y fais dès que possible. :)
![azvzg3c](https://cloud.githubusercontent.com/assets/2578321/7085732/f8194028-df79-11e4-83b0-634ae1d4b96d.gif)

Nico

**Comment by nico3333fr** [comment]
Et voilà, yavépuka et c'est fait :)

Merci bien ;)

**Comment by martinsam** [comment]
Il reste désormais à corriger la documentation : http://rocssti.net/guideline-rocssti-css "Table layout"
La mention col-noalign est toujours présente

**Comment by nico3333fr** [comment]
Bien vu, t'es trop fort ;)

C'est corrigé.
