### ISSUE TITLE
Guideline : Ajouter une explication

### ISSUE THREAD

**Issue by martinsam** [nico3333fr/ROCSSTI#20]
Juste un point de détail : 

Sur la vue http://rocssti.net/guideline-rocssti-css "Layout, mise en page" dernier paragraphe, il peut être utile d'ajouter une mention sur la classe "bl" pour display-block. Expliquer que cela est nécessaire pour  les labels + champs dans le cas présent,  puissent prendre leur place l'un au dessous de l'autre.

**Comment by nico3333fr** [comment]
Bien vu, c'est corrigé : http://rocssti.net/guideline-rocssti-css :)

Honnêtement, je n'avais pas précisé car en pratique j'entoure souvent les label par des paragraphes (un formulaire type que je fais : http://rocssti.net/guideline-rocssti-css )

Là pour l'exemple donné dans la guideline, j'avais voulu minimiser le code pour bien faire comprendre le inbl. :)

Encore merci !
