### ISSUE TITLE
Avoir une encre sur les onglets de la page http://rocssti.net/guideline-rocssti-css

### ISSUE THREAD

**Issue by martinsam** [nico3333fr/ROCSSTI#21]

**Comment by nico3333fr** [comment]
Hello,

en fait, ça marchait déjà : http://rocssti.net/guideline-rocssti-css#responsive 
(le plugin de tabs détecte s'il y a une ancre et choisit le tab en question)

mais comme j'utilisais une version très légèrement modifiée, ça ne "highlightait" pas le tab.

Du coup, c'est corrigé, merci pour l'avoir signalée. :+1:
